### ISSUE TITLE
CasterVoice PIP package fails to install: [Errno 2] No such file

### ISSUE THREAD

**Issue by LexiconCode** [dictation-toolbox/caster#381]
I had successfully installed yesterday the PIP package. With testing today I uninstalled via "pip uninstall castervoice" then reinstalled pip install castervoice.

Upon reinstalling the following error message is produced. 
watching the temp directory pip-install-(random) file appears during PIP install. Disappears one error messages triggered. It happens too fast for me to take a look at the file structure.

```
C:\Users\user>pip install castervoice
DEPRECATION: Python 2.7 will reach the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 won't be maintained after that date. A future version of pip will drop support for Python 2.7.
Collecting castervoice
  Using cached https://files.pythonhosted.org/packages/35/08/ff2669851b456674489074be2b4abfba6f0621d29a4174ccb0821d08b0a8/castervoice-0.6.8.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "c:\users\user\appdata\local\temp\pip-install-5xdhly\castervoice\setup.py", line 3, in <module>
        with open("README.md", "r") as fh:
    IOError: [Errno 2] No such file or directory: 'README.md'

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in c:\users\user\appdata\local\temp\pip-install-5xdhly\castervoice\
```

Note should "README.md" be ReadMe.md as reflected in the repository?

**Comment by LexiconCode** [comment]
Thanks! All right so it's fixed in https://github.com/dictation-toolbox/caster/commit/2194c8c848075b36e92c8a46aabccba71388842f
