### ISSUE TITLE
Legion not working correctly on second monitor

### ISSUE THREAD

**Issue by kendonB** [dictation-toolbox/Caster#502]
Legion grid doesn't work properly:

![image](https://user-images.githubusercontent.com/5327505/57394560-b6e63600-717a-11e9-8314-e8ac2082ef18.png)

Possibly related: https://github.com/dictation-toolbox/Caster/issues/172

**Comment by kendonB** [comment]
I tried resetting the scaling to 100%, then immediately got this error after saying "legion two":

```
grab_screen: Error calling GetDIBits. Returned 0.
action: Exception from function mouse_alternates:
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\dragonfly\actions\action_function.py", line 136, in _execute
    self._function(**arguments)
  File "C:\Users\kmbel\Documents\caster\castervoice\lib\navigation.py", line 238, in mouse_alternates
    ls.scan(bbox)
  File "C:\Users\kmbel\Documents\caster\castervoice\asynch\mouse\legion.py", line 188, in scan
    img = img.filter(ImageFilter.FIND_EDGES)
AttributeError: 'NoneType' object has no attribute 'filter'
action.exec: Execution failed: Function(mouse_alternates): 'NoneType' object has no attribute 'filter'
```

**Comment by kendonB** [comment]
This works fine on my Win 10 Dell laptop with a plugged in screen.

**Comment by kendonB** [comment]
This has been working for a while and I can't remember how it got fixed.
