### ISSUE TITLE
Userspace rules don't work after changing profile

### ISSUE THREAD

**Issue by seekM** [dictation-toolbox/Caster#508]
Example user rule in user space (`/.caster/rules` folder):
```
from dragonfly import Text

from castervoice.lib import control
from castervoice.lib.dfplus.merge.mergerule import MergeRule
from castervoice.lib.dfplus.state.short import R

class Decker(MergeRule):
    pronunciation = "decker"

    mapping = {
        "hit the deck": R(Text("shipwrecked"))
    }

def get_rule():
    return Decker()
```
Start DNS. Switch profiles (`Profile -> Open User Profile -> ...`). The following error message appears in the Natlink window:

```
Error loading _caster from C:\dev\Natlink-User\Caster\_caster.py
Traceback (most recent call last):
  File "C:\dev\NatLink\NatLink\MacroSystem\core\natlinkmain.py", line 331, in loadFile
    imp.load_module(modName,fndFile,fndName,fndDesc)
  File "C:\dev\Natlink-User\Caster\_caster.py", line 63, in <module>
    _NEXUS.process_user_content()
  File "C:\dev\Natlink-User\Caster\castervoice\lib\ctrl\nexus.py", line 47, in process_user_content
    self.merger.add_user_content(self.user_content_manager)
  File "C:\dev\Natlink-User\Caster\castervoice\lib\dfplus\merge\ccrmerger.py", line 145, in add_user_content
    self.add_global_rule(rule)
  File "C:\dev\Natlink-User\Caster\castervoice\lib\dfplus\merge\ccrmerger.py", line 118, in add_global_rule
    self._add_to(rule, self._global_rules)
  File "C:\dev\Natlink-User\Caster\castervoice\lib\dfplus\merge\ccrmerger.py", line 154, in _add_to
    raise Exception("Rule Naming Conflict: " + rule.get_pronunciation())
Exception: Rule Naming Conflict: decker
```

**Comment by LexiconCode** [comment]
That would make sense because if the user rules are loaded into the dragonfly engine and then reloaded into the engine when switching profiles. What to do about it per se I'm not hundred percent sure.

**Comment by LexiconCode** [comment]
Does Make userspace rules work after changing profile #511 fix this issue?

**Comment by seekM** [comment]
Yes, as stated in the description of #511 :)

**Comment by LexiconCode** [comment]
I'll see if I can get this merge tomorrow!
