### ISSUE TITLE
Caster fails on startup: KeyError: 'PROCESSOR_ARCHITEW6432'

### ISSUE THREAD

**Issue by rakeshnbabu** [dictation-toolbox/Caster#516]
Hello,

When starting up caster, dragonfly/lib/os.py threw a KeyError: 'PROCESSOR_ARCHITEW6432' The full error output is below:

```
(dragonfly) C:\Users\rbabu01\caster\Caster-master>python _caster.py
Searching Windows Registry For DNS...
Traceback (most recent call last):
  File "_caster.py", line 12, in <module>
    from caster.lib.ccr.standard import SymbolSpecs
  File "C:\Users\rbabu01\caster\Caster-master\caster\lib\ccr\__init__.py", line 3, in <module>
    from caster.lib import utilities
  File "C:\Users\rbabu01\caster\Caster-master\caster\lib\utilities.py", line 27, in <module>
    from caster.lib import settings
  File "C:\Users\rbabu01\caster\Caster-master\caster\lib\settings.py", line 139, in <module>
    "ENGINE_PATH": _validate_engine_path(),
  File "C:\Users\rbabu01\caster\Caster-master\caster\lib\settings.py", line 62, in _validate_engine_path
    return _find_natspeak()
  File "C:\Users\rbabu01\caster\Caster-master\caster\lib\settings.py", line 71, in _find_natspeak
    proc_arch64 = os.environ['PROCESSOR_ARCHITEW6432'].lower()
  File "C:\Users\rbabu01\AppData\Local\Continuum\anaconda3\envs\dragonfly\lib\os.py", line 425, in __getitem__
    return self.data[key.upper()]
KeyError: 'PROCESSOR_ARCHITEW6432'
```
I traced the error back to Caster-master\caster\lib\settings.py", line 71, in _find_natspeak
    proc_arch64 = os.environ['PROCESSOR_ARCHITEW6432'].lower() . The issue was that the environment variable "PROCESSOR_ARCHITEW6432" did not exist.

I am running Windows 10 64bit.
```
(dragonfly) C:\Users\rbabu01\caster\Caster-master>python
Python 2.7.16 |Anaconda, Inc.| (default, Mar 14 2019, 15:42:17) [MSC v.1500 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import os
>>> os.environ.keys()
['TMP', 'COMPUTERNAME', 'CONDA_PYTHON_EXE', 'USERDOMAIN', 'CONDA_PREFIX', 'DEFLOGDIR', 'PSMODULEPATH', 'COMMONPROGRAMFILES', 'PROCESSOR_IDENTIFIER', 'PROGRAMFILES', 'PROCESSOR_REVISION', 'PATH', 'SYSTEMROOT', 'PROGRAMFILES(X86)', 'COMSPEC', 'CONDA_SHLVL', 'TEMP', 'ORACLE_HOME', 'COMMONPROGRAMFILES(X86)', 'PROGRAMDATA', 'PROCESSOR_ARCHITECTURE', 'ALLUSERSPROFILE', 'LOCALAPPDATA', 'FPS_BROWSER_USER_PROFILE_STRING', 'HOMEPATH', 'UATDATA', 'PROGRAMW6432', 'USERNAME', 'CONDA_PREFIX_1', 'LOGONSERVER', 'PROMPT', 'CONDA_DEFAULT_ENV', 'R_LIBS', 'ONEDRIVE', 'CONDA_PROMPT_MODIFIER', 'FPS_BROWSER_APP_PROFILE_STRING', 'USERDNSDOMAIN', 'USERDOMAIN_ROAMINGPROFILE', 'PATHEXT', 'CONDA_EXE', 'SESSIONNAME', 'ONEDRIVECOMMERCIAL', 'WINDIR', 'APPDATA', 'HOMEDRIVE', 'SYSTEMDRIVE', 'NUMBER_OF_PROCESSORS', 'PROCESSOR_LEVEL', 'CI_HOLOS_CLI', 'COMMONPROGRAMW6432', 'OS', 'PUBLIC', 'USERPROFILE']
>>> os.environ['PROCESSOR_ARCHITECTURE']
'AMD64'
>>> os.environ['PROCESSOR_ARCHITEW6432']
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\rbabu01\AppData\Local\Continuum\anaconda3\envs\dragonfly\lib\os.py", line 425, in __getitem__
    return self.data[key.upper()]
KeyError: 'PROCESSOR_ARCHITEW6432'
```
The issue appears to be resolved if the first few lines of _find_natspeak in settings.py is changed from:
```
    print("Searching Windows Registry For DNS...")
    proc_arch = os.environ['PROCESSOR_ARCHITECTURE'].lower()
    proc_arch64 = os.environ['PROCESSOR_ARCHITEW6432'].lower()

```
to
```
    print("Searching Windows Registry For DNS...")
    proc_arch = os.environ['PROCESSOR_ARCHITECTURE'].lower()
    try:
        proc_arch64 = os.environ['PROCESSOR_ARCHITEW6432'].lower()
    except KeyError:
        proc_arch64 = False
```

**Comment by LexiconCode** [comment]
Welcome rakeshnbabu! I see from the stack trace your using Anaconda 3. I'm not sure that could lead to strange issues. Caster requires for now Python 2.7 32-bit. However you're more than welcome to make a pull request or I can integrate it later this week.

**Comment by rakeshnbabu** [comment]
In this case, the environment I'm running caster in is python 2.7 . Thanks for your help! You'll probably wind up integrating it before I get around to making a pull request, but I'll race you!
