### ISSUE TITLE
Store and Retrieve - OpenClipboard: Access denied

### ISSUE THREAD

**Issue by LexiconCode** [dictation-toolbox/Caster#657]
**Describe the bug**
When using a command that utilize the [store and retrieve](https://github.com/dictation-toolbox/Caster/blob/master/castervoice/lib/temporary.py). This is an issue with clipboard management. Technically this error could crop up with anything that relates to clipboard.
```
WARNING:action:Failed to store original clipboard contents: (5, 'OpenClipboard', 'Access is denied.')
``` 

**To Reproduce**
Note this is a infrequent bug.
1. Go to gitter
2. Highlight some text and say `insert link`
3. See error

**System:**
 - OS: Windows 10 64-bit
 - Program: gitter (or any other grammar that utilizes store and retrieve)

Fortunately later today it spit out the full trace back.

```Python
WARNING:action:Failed to store original clipboard contents: (5, 'OpenClipboard', 'Access is denied.')
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\dragonfly\engines\backend_natlink\engine.py", line 321, in results_callback
    r.process_recognition(root)
  File "C:\Python27\lib\site-packages\dragonfly\grammar\rule_mapping.py", line 216, in process_recognition
    self._process_recognition(item_value, extras)
  File "C:\Python27\lib\site-packages\dragonfly\grammar\rule_mapping.py", line 236, in _process_recognition
    value.execute(extras)
  File "C:\Python27\lib\site-packages\dragonfly\actions\action_base.py", line 189, in execute
    self._action.execute(data)
  File "C:\Python27\lib\site-packages\dragonfly\actions\action_base.py", line 92, in execute
    if self._execute(data) == False:
  File "D:\Backup\Library\Documents\Caster\castervoice\lib\dfplus\state\actions.py", line 30, in _execute
    self.nexus().state.add(StackItemRegisteredAction(self, data))
  File "D:\Backup\Library\Documents\Caster\castervoice\lib\dfplus\state\stack.py", line 28, in add
    self.stack.add(stack_item)
  File "D:\Backup\Library\Documents\Caster\castervoice\lib\dfplus\state\stack.py", line 121, in add
    stack_item.execute()
  File "D:\Backup\Library\Documents\Caster\castervoice\lib\dfplus\state\stackitems.py", line 42, in execute
    self.base.execute(self.dragonfly_data)
  File "C:\Python27\lib\site-packages\dragonfly\actions\action_base.py", line 218, in execute
    action.execute(data)
  File "C:\Python27\lib\site-packages\dragonfly\actions\action_base.py", line 92, in execute
    if self._execute(data) == False:
  File "D:\Backup\Library\Documents\Caster\castervoice\lib\temporary.py", line 64, in _execute
    Paste(output).execute()
  File "C:\Python27\lib\site-packages\dragonfly\actions\action_base.py", line 92, in execute
    if self._execute(data) == False:
  File "C:\Python27\lib\site-packages\dragonfly\actions\action_base.py", line 141, in _execute
    self._execute_events(self._events)
  File "C:\Python27\lib\site-packages\dragonfly\actions\action_paste.py", line 125, in _execute_events
    clipboard.copy_to_system()
  File "C:\Python27\lib\site-packages\dragonfly\windows\clipboard.py", line 182, in copy_to_system
    win32clipboard.OpenClipboard()
pywintypes.error: (5, 'OpenClipboard', 'Access is denied.')
```

**Comment by Danesprite** [comment]
This problem is not really Caster specific. It occurs only sometimes because the Windows clipboard is a shared resource and can be locked by an application at any moment ([see this](https://stackoverflow.com/questions/1859102/how-can-i-fix-cannot-open-clipboard-access-denied-errors)). My guess is that your browser (or the gitter app?) is locking the clipboard frequently and dragonfly tried to open it while the other application was still accessing it.

Caster already has some try catch loops for handling this problem, such as in `navigation.py`: https://github.com/dictation-toolbox/Caster/blob/afb1dd1d97d22883f608f325a1b8d294b7bd8720/castervoice/lib/navigation.py#L89-L110

Dragonfly's `Paste` action needs to handle all access operations, not just the first one. This is why you got a warning the first time and an exception trace later. I'm not sure if this problem also occurs with the `pyperclip` clipboard class.
