### ISSUE TITLE
Pip Install Bug

### ISSUE THREAD

**Issue by ethangoldstein** [dictation-toolbox/Caster#688]
I tried installing caster through PIP. I got the following error.

Generic Exception: Traceback (most recent call last):
  File "c:\users\egoldste\appdata\local\temp\pip-install-rf5jki\castervoice\post_setup.py", line 39, in setup
    shutil.copy("_caster.py", directory)
  File "c:\python27\lib\shutil.py", line 119, in copy
    copyfile(src, dst)
  File "c:\python27\lib\shutil.py", line 69, in copyfile
    raise Error("`%s` and `%s` are the same file" % (src, dst))
Error: `_caster.py` and `.\_caster.py` are the same file

Caster: Report Error to https://github.com/dictation-toolbox/caster/issues

Close window to continue

c:\users\egoldste\appdata\local\temp\pip-install-rf5jki\castervoice>

When I rerun the PIP command, PIP thinks that caster has been installed correctly and does not attempt to fix this problem. I had to delete caster from python manually to reproduce this error.

**Comment by LexiconCode** [comment]
Thanks for reporting this issue! The PIP install this very alpha and won't go live until the ccr rewrite and a couple of other features.

**Comment by ethangoldstein** [comment]
Sorry, I wasn't clear. While the PIP uninstall did not work properly, I was able to remove the package by simply deleting the castervoice folder from the Python2 directory.

**Comment by LexiconCode** [comment]
@ethangoldstein 

Could you try executing the following in your Python environment? The following code should print the absolute path to your natlink user directory.
```
import natlinkstatus
status = natlinkstatus.NatlinkStatus()
directory = status.getUserDirectory()
print directory 
```

**Comment by ethangoldstein** [comment]
The results are:

UserDirectory: .
.
[Finished in 1.3s]

**Comment by LexiconCode** [comment]
What version of Natlink do you have installed?
What is your current Natlink UserDirectory absolute path via `Configure Natlink via GUI`?
![image](https://user-images.githubusercontent.com/24551569/66518139-2e155280-eaaa-11e9-97a4-68b092059777.png)

**Comment by ethangoldstein** [comment]
![Untitled](https://user-images.githubusercontent.com/19829073/66795660-21ce3280-eeba-11e9-8813-0944d6ed7781.png)

**Comment by LexiconCode** [comment]
@ethangoldstein 
Update to [natlink-4.2](https://sourceforge.net/projects/natlink/files/natlink/natlink4.2/setup-natlink-4.2.exe/download)

rerun to test
```
import natlinkstatus
status = natlinkstatus.NatlinkStatus()
directory = status.getUserDirectory()
print directory 
```

**Comment by LexiconCode** [comment]
This error also occurs if you try to use `python setup.py install`. So some further error handling is needed.

However however the post install script is trying to address where to place `_caster.py` so that natlink or other engine loaders can load Caster.
