### ISSUE TITLE
Simple filtered rule replacing a spec `comma` with an alternative produces a crash

### ISSUE THREAD

**Issue by LexiconCode** [dictation-toolbox/Caster#689]
**Describe the bug**
Creating a Simple filtered rule using `words.txt` replacing a spec `comma` causes a crash as described below caster initialization.

Note: This issue could not be reproduced in the CCR rewrite.

Traceback
```
Error loading _caster from C:\Users\dusty\Documents\Caster\_caster.py
Traceback (most recent call last):
  File "C:\NatLink\NatLink\MacroSystem\core\natlinkmain.py", line 331, in loadFile
    imp.load_module(modName,fndFile,fndName,fndDesc)
  File "C:\Users\dusty\Documents\Caster\_caster.py", line 37, in <module>
    from castervoice.lib.ccr.recording import bringme, again, alias, history
  File "C:\Users\dusty\Documents\Caster\castervoice\lib\ccr\recording\bringme.py", line 191, in <module>
    control.non_ccr_app_rule(BringRule(), context=None, rdp=False, filter=True)
  File "C:\Users\dusty\Documents\Caster\castervoice\lib\control.py", line 28, in non_ccr_app_rule
    if filter: gfilter.run_on(rule)
  File "C:\Users\dusty\Documents\Caster\castervoice\lib\dfplus\merge\gfilter.py", line 232, in run_on
    spec_override_from_config(mp)
  File "C:\Users\dusty\Documents\Caster\castervoice\lib\dfplus\merge\gfilter.py", line 222, in spec_override_from_config
    rule._mcontext, rule._mwith)
TypeError: __init__() takes exactly 1 argument (11 given)
```

**To Reproduce**
Steps to reproduce the behavior (be sure to include the exact command phrase you are using):
1. Create `words.txt` with the following
```
<<<SPEC>>>
comma -> hang
```
2. Then reboot Castor
3. See error on initialization

**Expected behavior**
Caster should not crash. 

**Extra information**
The error does not occur with the following
```
<<<NOT_SPECS>>>
comma -> hang
```
As a result "hang ace" now inserts ", " as expected.

**Comment by LexiconCode** [comment]
Resolved in caster 1.0.0
