### ISSUE TITLE
Basic sanity check for alias

### ISSUE THREAD

**Issue by LexiconCode** [dictation-toolbox/Caster#694]
**Describe the bug**

ERROR:compound.parse:Invalid compound spec: u'us:'

Which is due to an invalid spec due to `:` within the command name. all command names must be `words` without special characters.

```Toml
[single_aliases]
"list:" = "list :"
```

"list:" should be "list colon"

full trace back
```Python
ERROR:compound.parse:Invalid compound spec: u'list:'
Error loading _caster from C:\Users\Gaute\Documents\caster\_caster.py
Traceback (most recent call last):
  File "C:\NatLink\NatLink\MacroSystem\core\natlinkmain.py", line 331, in loadFile
    imp.load_module(modName,fndFile,fndName,fndDesc)
  File "C:\Users\Gaute\Documents\caster\_caster.py", line 37, in <module>
    from castervoice.lib.ccr.recording import bringme, again, alias, history
  File "C:\Users\Gaute\Documents\caster\castervoice\lib\ccr\recording\alias.py", line 94, in <module>
    control.non_ccr_app_rule(Alias(_NEXUS), context=None, rdp=False, filter=False)
  File "C:\Users\Gaute\Documents\caster\castervoice\lib\ccr\recording\alias.py", line 21, in __init__
    SelfModifyingRule.__init__(self)
  File "C:\Users\Gaute\Documents\caster\castervoice\lib\dfplus\merge\selfmodrule.py", line 28, in __init__
    if refresh: self.refresh()
  File "C:\Users\Gaute\Documents\caster\castervoice\lib\ccr\recording\alias.py", line 64, in refresh
    self.reset(mapping)
  File "C:\Users\Gaute\Documents\caster\castervoice\lib\dfplus\merge\selfmodrule.py", line 49, in reset
    self.context)
  File "C:\Users\Gaute\Documents\caster\castervoice\lib\dfplus\merge\mergerule.py", line 69, in __init__
    MappingRule.__init__(self, name, mapping, extras, defaults, exported)
  File "C:\Python27\lib\site-packages\dragonfly\grammar\rule_mapping.py", line 147, in __init__
    c = Compound(spec, elements=self._extras, value=value)
  File "C:\Python27\lib\site-packages\dragonfly\grammar\elements_compound.py", line 287, in __init__
    raise SyntaxError("Invalid compound spec: %r" % spec)
SyntaxError: Invalid compound spec: u'list:' ```

**Comment by kendonB** [comment]
@LexiconCode is this one solved? I just tried this by manually editing `sm_aliases.toml` directly. The current behavior is that it strips out the special characters, which seems like reasonable behavior to me.

**Comment by LexiconCode** [comment]
> 
> 
> @LexiconCode is this one solved? I just tried this by manually editing `sm_aliases.toml` directly. The current behavior is that it strips out the special characters, which seems like reasonable behavior to me.

Confirmed testing now that it is not fixed. I think below we add Python RegEx to remove all special characters.

https://github.com/dictation-toolbox/Caster/blob/c1c3e7e8b60c4bdd6f1af867d5b33f160f405864/castervoice/rules/ccr/recording_rules/alias/base_alias.py#L41
or
https://github.com/dictation-toolbox/Caster/blob/c1c3e7e8b60c4bdd6f1af867d5b33f160f405864/castervoice/rules/ccr/recording_rules/alias/base_alias.py#L55

**Comment by LexiconCode** [comment]
Okay I have a fix for this and coming using re. It only allows uppercase/lowercase characters and apostrophes. When anything else is found it's replaced with `""`

https://github.com/dictation-toolbox/Caster/compare/master...LexiconCode:sterilize_spec_input_
