### ISSUE TITLE
Error while running Formatting Hook 

### ISSUE THREAD

**Issue by LexiconCode** [dictation-toolbox/Caster#726]
**Describe the bug**
FormattingHook is supposed to report changes in Formatting events. The following occurs on startup with FormattingHook enabled.

```
Error while running hook <format_hook.FormattingHook object at 0x255975D0> with activation event.
The rule GrammarActivatorRule was set to active.
Error while running hook <format_hook.FormattingHook object at 0x255975D0> with activation event.
The rule HooksActivationRule was set to active.
```
**To Reproduce**
Steps to reproduce the behavior (be sure to include the exact command phrase you are using):
1. Go to 'hooks.toml'
2. set 'FormattingHook = true'
3. Restart DNS
4. See error in status window

I believe this may be related to the following.
Apparently despite loading with toml `.value` can tomlkit still uses its own classes to represent real numbers instead of Python built-in which is undesirable.

**Comment by kendonB** [comment]
```
Error while running hook <format_hook.FormattingHook object at 0x00000000534D3EB8> with activation event.

Traceback (most recent call last):
  File "castervoice\lib\merge\ccrmerging2\hooks\hooks_runner.py", line 61, in execute
    hook.run(event)
  File "C:\Users\kmbel\Documents\caster\castervoice\lib\merge\ccrmerging2\hooks\standard_hooks\format_hook.py", line 32, in run
    pronunciation = event_content["pronunciation"]
TypeError: 'RuleActivationEvent' object has no attribute '__getitem__'
The rule GrammarActivatorRule was set to active.
INFO:engine:Loading grammar g2
Error while running hook <format_hook.FormattingHook object at 0x00000000534D3EB8> with activation event.

Traceback (most recent call last):
  File "castervoice\lib\merge\ccrmerging2\hooks\hooks_runner.py", line 61, in execute
    hook.run(event)
  File "C:\Users\kmbel\Documents\caster\castervoice\lib\merge\ccrmerging2\hooks\standard_hooks\format_hook.py", line 32, in run
    pronunciation = event_content["pronunciation"]
TypeError: 'RuleActivationEvent' object has no attribute '__getitem__'
The rule HooksActivationRule was set to active.
INFO:engine:Loading grammar g3
Error while running hook <format_hook.FormattingHook object at 0x00000000534D3EB8> with activation event.

Traceback (most recent call last):
  File "castervoice\lib\merge\ccrmerging2\hooks\hooks_runner.py", line 61, in execute
    hook.run(event)
  File "C:\Users\kmbel\Documents\caster\castervoice\lib\merge\ccrmerging2\hooks\standard_hooks\format_hook.py", line 32, in run
    pronunciation = event_content["pronunciation"]
TypeError: 'RuleActivationEvent' object has no attribute '__getitem__'
```
this is the error that I see

**Comment by kendonB** [comment]
It looks like maybe my error is related to the fact that some rules pronunciations come through the `pronunciation` attribute and some come through the `name` attribute. This is a weird inconsistency and maybe should be altered?
