### ISSUE TITLE
legion not working with kaldi

### ISSUE THREAD

**Issue by kendonB** [dictation-toolbox/Caster#795]
**Describe the bug**
Legion not working with kaldi.

**To Reproduce**
Steps to reproduce the behavior (be sure to include the exact command phrase you are using):
1. Run caster with kaldi
2. Say 'Legion'

**Expected behavior**
Legion should work.

```
MouseAlternatives: legion [<monitor>], %(monitor)s
DEBUG:action.exec:Executing action: 'mouse_alternates'()+'focus_mousegrid'() ({'_node': Node: Alternative(...), [u'legion'], '_grammar': Grammar(g7), '_rule': MouseAlternativesRule(mouse alternatives rule)})
DEBUG:action.exec:Executing action: 'mouse_alternates'() ({'_node': Node: Alternative(...), [u'legion'], '_grammar': Grammar(g7), '_rule': MouseAlternativesRule(mouse alternatives rule)})
Legion loading failed with '[Error 126] The specified module could not be found'
ERROR:action:Exception from function mouse_alternates:
Traceback (most recent call last):
  File "C:\Python27_64\lib\site-packages\dragonfly\actions\action_function.py", line 145, in _execute
    self._function(**arguments)
  File "castervoice\lib\navigation.py", line 38, in mouse_alternates
    ls = LegionScanner()
  File "castervoice\asynch\mouse\legion.py", line 168, in __init__
    self.setup_dll()
  File "castervoice\asynch\mouse\legion.py", line 186, in setup_dll
    self.tirg_dll.getTextBBoxesFromFile.argtypes = [c_char_p, c_int, c_int]
AttributeError: 'NoneType' object has no attribute 'getTextBBoxesFromFile'
ERROR:action.exec:Execution failed: 'mouse_alternates'(): 'NoneType' object has no attribute 'getTextBBoxesFromFile'
ERROR:action.exec:Execution failed: 'mouse_alternates'()+'focus_mousegrid'()
```
**System:**
 - OS: Windows
 - Program: Legion
 - Version: Latest master

**Comment by kendonB** [comment]
Could this just be a 32 bit vs 64 bit problem?

**Comment by kendonB** [comment]
rtfming worked to fix this.

**Comment by kendonB** [comment]
Docs suggest that an up to date Windows 10 will have that required package which may not be true, though, I did mess with those packages a while back so this may not be a problem generally.
