### ISSUE TITLE
Legion error with Kaldi - a bytes-like object is required, not 'str'

### ISSUE THREAD

**Issue by AaronHeady** [dictation-toolbox/Caster#838]
**Describe the bug**
Legion not working with kaldi.

**To Reproduce**
Steps to reproduce the behavior (be sure to include the exact command phrase you are using):
1. Run caster with kaldi
2. Say 'Legion'

**Expected behavior**
Legion works

**Screenshots**
```
*- Starting Caster v 1.6.16 -*
INFO:engine:Listening...
DEBUG:action.exec:Executing action: RegisteredAction() ({'_grammar': Grammar(g6), '_rule': MouseAlternativesRule(mouse alternatives rule), '_node': Node: Alternative(...), ['legion'], 'rough': True})
MouseAlternatives: legion [<monitor>] [<rough>], %(monitor)s, %(rough)s
DEBUG:action.exec:Executing action: 'mouse_alternates'()+'focus_mousegrid'() ({'_grammar': Grammar(g6), '_rule': MouseAlternativesRule(mouse alternatives rule), '_node': Node: Alternative(...), ['legion'], 'rough': True})
DEBUG:action.exec:Executing action: 'mouse_alternates'() ({'_grammar': Grammar(g6), '_rule': MouseAlternativesRule(mouse alternatives rule), '_node': Node: Alternative(...), ['legion'], 'rough': True})
Legion loading failed with 'a bytes-like object is required, not 'str''
ERROR:action:Exception from function mouse_alternates:
Traceback (most recent call last):
  File "D:\Python\Python38\lib\site-packages\dragonfly\actions\action_function.py", line 145, in _execute
    self._function(**arguments)
  File "D:\Caster\castervoice\lib\navigation.py", line 39, in mouse_alternates
    ls = LegionScanner()
  File "D:\Caster\castervoice\asynch\mouse\legion.py", line 168, in __init__
    self.setup_dll()
  File "D:\Caster\castervoice\asynch\mouse\legion.py", line 186, in setup_dll
    self.tirg_dll.getTextBBoxesFromFile.argtypes = [c_char_p, c_int, c_int]
AttributeError: 'NoneType' object has no attribute 'getTextBBoxesFromFile'
ERROR:action.exec:Execution failed: 'mouse_alternates'(): 'NoneType' object has no attribute 'getTextBBoxesFromFile'
ERROR:action.exec:Execution failed: 'mouse_alternates'()+'focus_mousegrid'()
```

**System:**
-OS: Windows 10 with Python 3.8.5 x64
-Program: Legion
-Version: Latest master as of 30 July 2020

**Comment by LexiconCode** [comment]
AaronHeady thanks for the report! It is the last grid that needs to be to be ported to Python 3 but also the most difficult.

**Comment by AaronHeady** [comment]
> 
> 
> AaronHeady thanks for the report! It is the last grid that needs to be to be ported to Python 3 but also the most difficult.

I'm having trouble with Sudoku also, just a weird sort of hazy overlay on the screen. Haven't checked it for an error yet. Really loving how well Castor works. Thanks.

**Comment by LexiconCode** [comment]
You're welcome, by chance do you use two monitors. Sudoku grid has an has an open issue.
