### ISSUE TITLE
Can't install on w10 with the WSR bat file. output says it cant install wheels for regex and wxpthon

### ISSUE THREAD

**Issue by josegarciacarreno** [dictation-toolbox/Caster#948]
Then follows a long explanation about how "license-file" will fail ln dist.py, although I can find no ocurrence of this. Moreover, there is a dead-link supposed to give further details.
I have the python312\python.exe system path , don't know what else to do.
**System:**
 - OS: [windows 10]
 - installation procedure.
 -

**Comment by josegarciacarreno** [comment]
EDIT: instead  of build I imported manually the required modules. Then everything is OK except for a function that reloads modules:
ERROR:module:CommandModule('_caster.py'): Error loading module: No module named 'imp'
Traceback (most recent call last):
  File "C:\Users\Usuario\Caster\castervoice\lib\ctrl\mgr\loading\load\reload_fn_provider.py", line 8, in get_reload_fn
    reload
UnboundLocalError: cannot access local variable 'reload' where it is not associated with a value

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Python312\Lib\site-packages\dragonfly\loader.py", line 65, in load
    exec(compile(contents, self._path, 'exec'), namespace)
  File "C:\Users\Usuario\Caster\_caster.py", line 38, in <module>
    _content_loader = ContentLoader(_crg, importlib.import_module, _rp.get_reload_fn(), _sma)
                                                                   ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Usuario\Caster\castervoice\lib\ctrl\mgr\loading\load\reload_fn_provider.py", line 11, in get_reload_fn
    from imp import reload
ModuleNotFoundError: No module named 'imp'

**Comment by josegarciacarreno** [comment]
But after setting manually the requirements it seems now  only a matter of fixing that function that reloads, or its not? My python is not really pro level...

**Comment by LexiconCode** [comment]
A reasonable question.  The reason 'imp' module can be found is because it's no longer included in the standard library and newer versions of Python.

Deprecated since version 3.4: The [imp](https://docs.python.org/3.10/library/imp.html#module-imp) module is deprecated in favor of [importlib](https://docs.python.org/3.10/library/importlib.html#module-importlib). Which is been fixed in [DropPy2](https://github.com/dictation-toolbox/Caster/tree/DropPy2?rgh-link-date=2024-09-26T12%3A51%3A41Z)

**Comment by LexiconCode** [comment]
I'm updating the master branch including the changes from [DropPy2](https://github.com/dictation-toolbox/Caster/tree/DropPy2?rgh-link-date=2024-09-27T12%3A45%3A33Z) which will soon be deleted.

**Comment by kendonB** [comment]
Looks out of date / dealt with.
